name: release

on:
  push:
    tags:
      - v*.*.*
      - v*.*-Beta*
      - v*.*-ExeBeta*
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup npm
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Frontend Build
        run: npm run build
        working-directory: frontend

      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser-xray_pool.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
